
# environment.yml for CAD with Python, build123d, ocp_vscode

channels:
  - conda-forge
  #- defaults
dependencies:
  - build123d
  #- cadquery
  #- freecad
  - pydantic
  - ipykernel
  - ruff
  - pytest
  - pip
  - pip:
    - ocp_vscode>=2.8.5
  #  - jupyter-cadquery